version: '3'
services:
  api:
    image: "sitesmonitoring-api"
    build: .
    depends_on:
     - postgres
    ports:
     - "5000:80"
    environment:
     - ASPNETCORE_ENVIRONMENT=Production
  postgres:
    image: "postgres:latest"
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_HOST_AUTH_METHOD=trust